name: NetherWaterPlacement
version: 1.0.0
main: com.wolf.netherwaterplacement.NetherWaterPlacement
api-version: 1.13
author: Wolf
description: Позволяет игрокам с определённым правом ставить воду в Аду
website: https://t.me/zxzniktozxz
softdepend: [LuckPerms]

permissions:
  netherwaterplacement.place:
    description: Позволяет ставить воду в Аду
    default: false
  netherwaterplacement.*:
    description: Все права плагина
    default: op
    children:
      netherwaterplacement.place: true
